---
title: "p8105_hw6_smm2350"
author: "Shaina Mackin"
date: "12/1/2021"
output: github_document
---

# Homework 6

To begin, I'll load libraries and set themes.

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

I'll first load the birthweight dataset...
```{r import1}
bwt_data = read.csv("/Users/shainamackin/Desktop/Fall 2021/Data Science I/p8105_hw6_smm2350/data/birthweight.csv")
```

... and then clean it by tidying variable names and factoring when relevant so that it's ready for regression analysis. 
```{r clean1}
bwt_df = bwt_data %>%
  janitor::clean_names() %>%
  mutate(
    babysex = factor(babysex),
    frace = factor(frace),
    malform = factor(malform),
    mrace = factor(mrace)
  ) %>%
  mutate(
    babysex = fct_recode(babysex, "male" = '1'),
    babysex = fct_recode(babysex, "female" = '2'),
    frace = fct_recode(frace, "white" = '1'),
    frace = fct_recode(frace, "black" = '2'),
    frace = fct_recode(frace, "asian" = '3'),
    frace = fct_recode(frace, "puerto rican" = '4'),
    frace = fct_recode(frace, "other" = '8'),
    malform = fct_recode(malform, "absent" = '0'),
    malform = fct_recode(malform, "present" = '1'),
    mrace = fct_recode(mrace, "white" = '1'),
    mrace = fct_recode(mrace, "black" = '2'),
    mrace = fct_recode(mrace, "asian" = '3'),
    mrace = fct_recode(mrace, "puerto rican" = '4'))
```

## Problem 2

```{r import2}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


